# Generated by Django 5.2.17 on 2026-10-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('register_time', models.DateTimeField()),
                ('tipo_registro', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'registros',
                'ordering': ['-register_time', '-id_registro'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id_biometrico', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=20)),
                ('sn', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('usuario', models.CharField(blank=True, max_length=30, null=True)),
                ('contrasena', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'biometricos',
                'ordering': ['id_biometrico'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_empleado', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('turno', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.BooleanField()),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'ordering': ['nombre', 'id_empleado'],
                'managed': False,
            },
        ),
    ]
